apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: volume-example
spec:
 containers: 
 - name: app1
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
   volumeMounts:
   - mountPath: /storage
     name: app-storage
 - name: app2
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 80
   volumeMounts:
   - mountPath: /storage
     name: app-storage
 volumes:
  - name: app-storage
    hostPath:
     path: /tmp/files
