apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /tmp/files
      name: app-storage
  volumes:
  - name: app-storage
    hostPath:
      # directory location on host
      path: /tmp/files
      # this field is optional
---

apiVersion: v1
kind: Pod
metadata:
  name: animals
spec:
  containers:
  - name: animals
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80
        volumeMounts:
    - mountPath: /tmp/files
      name: app-storage
  volumes:
  - name: app-storage
    hostPath:
      # directory location on host
      path: /tmp/files
      # this field is optional
